### ISSUE TITLE
Nothing is displayed for single nodes in the `traffic`

### ISSUE THREAD

**Issue by tmr08c** [erlanglab/erlangpl-ui#29]
When going to `/traffic` in Chrome and Safari with a single node running there is not visual representation of that node (included DevTools console in hopes that would help):

<img width="936" alt="screen shot 2017-04-03 at 10 22 40 pm" src="https://cloud.githubusercontent.com/assets/691365/24639240/50ba5050-18bc-11e7-88d2-8bd81c308157.png">

If I mouse around I am able to get the hand icon and click into the nothingness and get into the traffic view for that node.

In Firefox it doesn't get past the loading image and has an error in the console:

<img width="887" alt="screen shot 2017-04-03 at 10 33 52 pm" src="https://cloud.githubusercontent.com/assets/691365/24639455/b88ce4d0-18bd-11e7-956a-6367ae26aec4.png">

I'm not familiar with browser support of WebGL so I'm not which browser was best to check with.

```
> node --version
v6.9.1
> elm --version
0.18.0
```

Please let me know if I am missing anything or could provide more information.

**Comment by Baransu** [comment]
Empty view with one node is underlaying Vizceral issue. It's [fixed](https://github.com/Netflix/vizceral/pull/59) already be we have to update our data model to support this version. You can expect fix soon. :)

Thank you for your feedback 😃
