### ISSUE TITLE
Add better vizceral loader image

### ISSUE THREAD

**Issue by Baransu** [erlanglab/erlangpl-ui#4]
Right now we're using some image and logo, which are not transparent. We have to change it to one image with transparent background.

Right now loader only blinks but when we'll connect to real data we'll have to wait for first set of data to show the graph and loader will be shown for a much longer time than it is right now.

**Comment by michalslaski** [comment]
@Baransu here is a set of hi and low resolution PNG files with the erlangpl logo and icon. Let me know if you need anything more. Feel free to use them as you see fit.

![erlangpl_icon_90](https://cloud.githubusercontent.com/assets/376556/23785012/ac30316c-0565-11e7-9399-ca18d693c000.png)
![erlangpl_icon_250](https://cloud.githubusercontent.com/assets/376556/23785010/ac3025f0-0565-11e7-83ab-fb191973bce7.png)
![erlangpl_log_low_res](https://cloud.githubusercontent.com/assets/376556/23785009/ac2fc808-0565-11e7-835d-821cc11c065d.png)
![erlangpl_logo_hi_res](https://cloud.githubusercontent.com/assets/376556/23785011/ac302212-0565-11e7-8ba4-a53b0935b9f1.png)

**Comment by Baransu** [comment]
Thank you a lot!

**Comment by Baransu** [comment]
I've decided to move branding to `/about` page so now loader has no image.
