### ISSUE TITLE
Add content to /about view

### ISSUE THREAD

**Issue by Baransu** [erlanglab/erlangpl-ui#7]
This view should contain some copyright info, change log, contact, webpage, link to documentation, etc.

It's important because it's written in Elm as out example how to integrate Elm within `erlangpl`. Being simple static view it's still value to have it written in Elm to show how any Elm view can be written.

**Comment by michalslaski** [comment]
Erlang Performance Lab v0.4.0

erlangpl is a tool for developers working with the Erlang VM (BEAM).
It helps to observe the system and analyze its performance.

github: https://github.com/erlanglab
www: http://www.erlang.pl
twitter: https://twitter.com/erlanglab
license: [Apache 2.0](http://apache.org/licenses/LICENSE-2.0)

**Comment by michalslaski** [comment]
@Baransu feel free to extend the About file as you see fit. The above comment is an example.

Do you want to try to read the version number from localhost:8000 and this way show how Elm-based application can execute some simple request to the cowboy server?

**Comment by Baransu** [comment]
Good idea. Something like this would be great.
```json
{
  "version": "0.4"
}
```

**Comment by michalslaski** [comment]
Added new plugin returning version of the epl application (https://github.com/erlanglab/erlangpl/commit/94c5304ea014e041acd9e7339b4624eaf6359e7c)

```
$ curl localhost:8000/epl_version_EPL
{"version":"0.3.0"}
```

**Comment by Baransu** [comment]
Awesome, I'll add it today!
