### ISSUE TITLE
epl-sup-tree plugin

### ISSUE THREAD

**Issue by Baransu** [erlanglab/erlangpl-ui#9]
@arkgil [said](https://github.com/erlanglab/erlangpl/issues/10#issuecomment-284188068) he's experimenting with this view. The idea is to have supervisor tree, the similar to Erlang observer.

Idea is to implement it with [http://sigmajs.org/](http://sigmajs.org/) library because it has look we're interested in.

Plugin should export React component, reducer and socket listeners if is listening to any.

**Comment by arkgil** [comment]
Followup to discussion from erlanglab/erlangpl#11 .

Unfortunately `epl_sup_tree` is currently not direct dependency of `erlangpl` so to start it one needs to:
* clone the repo
* compile it using `rebar3 compile` (you need `rebar3` installed)
* start `erlangpl` with additional flag: `-p path/to/epl_sup_tree/_build/default/lib/epl_st`

This way plugin is loaded and we can create WebSocket connections to `localhost:8000/epl_st_EPL`.

There are only two types of messages sent to a client:
* `apps-info` topic - this is an object of applications started on monitored node. Structure of the message looks roughly like this:

```js
{
  app_one: {
    id: <x.y.z>, // this is text representation of a PID,
    type: ..., // this can be either "worker" or "supervisor"
    children: [
      {id: ..., type: ..., children: [...]},
      ...
    ]
  }
}
```

So it is just a tree structure with some metadata - id and type of process (I used type to render workers and supervisors in different colors). Worker type nodes never have children (so children array is empty). Keys of the top level object are application names. That's all what is needed to draw a tree in the browser.

* `node-info` topic - this is sent only when client requests info about one of the nodes (i.e. sends id of a node through the connection). Structure of the message is:

```js
{
  id: <x.y.z> // id of the node (once again a PID),
  info: ... // this is an object with data returned by call to `erlang:process_info/1`.
              //For now it's okay to render JSON representation of this object in some div
}
```

That's it. Updates are sent every 5 seconds, similar to `epl_dashboard` plugin.

@Baransu let me know if you have any questions!

**Comment by arkgil** [comment]
Oh, and for graph rendering MIchał recommended https://github.com/anvaka/VivaGraphJS, which seems to be faster than Sigma, and also has cleaner API imo.

**Comment by Baransu** [comment]
Looks good. When i'll stumble into some issue I let you know.

**Comment by Baransu** [comment]
@arkgil I can see only `epl_st` topic.

**Comment by arkgil** [comment]
Sorry, forgot to merge  branch. Please update to new master.

**Comment by Baransu** [comment]
How can I request info about node?

**Comment by Baransu** [comment]
I've realized right now I don't have API to send messages back to server 😄

**Comment by arkgil** [comment]
Simply send anything through the connection. By "node" I meant node in a tree (a vertex), so that might have been a little confusing. If you send a valid PID, it will be looked up and info about process will be sent back.

**Comment by arkgil** [comment]
If you have some propositions about this API, please tell. I'd be happy to make it more understandable/readable/easy-to-use.

**Comment by Baransu** [comment]
@arkgil how much sup-tree can change during runtime?

**Comment by arkgil** [comment]
A lot 😄  But it would be pretty simple to send to a client info about which processes from the tree need to be deleted or added. But that would require some more detailed planning. For now I'd recommend re-drawing every the update is sent (let's not worry about performance now).

Would you be able to design it in such way, that user can select which trees are rendered at a time? e.g. he can choose to see 2 trees at once, 1, or none.

And I don't know if I was clear enough, but each key of `apps-info` topic object represent different OTP application, so each key is a root of different tree.

**Comment by Baransu** [comment]
Problem with re-drawing is that `VivaGraphJS` have fancy animations, user can zoom in/out, move view so redrawing would be very disturbing experience. I'll come up with some solution. But important thing is. If for example supervisor has 3 workers can he change it to 3 supervisors with 3 workers each for example, and pid would be the same or it would be new supervisor with new pid? Because I'm thinking of simple solution that remove branch that changed and replace it with new branch, or new nested branch is created.

Yeah, I can create some side panel with list of all applications so user can select which to display.

**Comment by arkgil** [comment]
Oh, I see. So maybe I should find some time to implement sending info about spawned and exiting processes. Given some fancy application logic, or just logic which assumes processes to die often, trees may change completely over time (change of pid is almost guaranteed when process is restarted). For now we have to live with what we got, I'll think about extending API.

**Comment by Baransu** [comment]
I was wrong about that disturbing experience. It turns out to feel pretty ok. It work for now, we'll focus on performance and better design latter.

**Comment by arkgil** [comment]
Great!

**Comment by Baransu** [comment]
Ok, we have to slow down physics a loooooooooooot. I've just spawned whole tree for phoenix based app with bunch of supervisors and workers containing every possible hex color, and everything just blew up 😄

**Comment by Baransu** [comment]
@arkgil I think I have to create root node (if more than one tree is present) which is above every OTP application. It's not perfect but helps with rendering large projects.

**Comment by Baransu** [comment]
![screen shot 2017-03-06 at 23 53 58 2](https://cloud.githubusercontent.com/assets/9558691/23633980/360e6336-02c8-11e7-98de-3aaa41b71091.png)

**Comment by Baransu** [comment]
![screen shot 2017-03-07 at 00 39 01](https://cloud.githubusercontent.com/assets/9558691/23635177/81f840e0-02ce-11e7-9cf5-b9a5a7d1fd52.png)

**Comment by arkgil** [comment]
Awesome! And can you click on the node to see the info about it?

Is it your Phoenix app?

**Comment by Baransu** [comment]
My problem with VivaGraphJS is physics. I'll probably look into different lib for that for comparison.

**Comment by michalslaski** [comment]
@Baransu if you have issues with integrating VivaGraphJS, try asking @anvaka for help. He seems to be very committed to open source (pun intended).

**Comment by Baransu** [comment]
I figured it out, maybe not a perfect setup but it's good for now.
